/*
2 queries seperate

SELECT CITY, LENGTH(CITY) AS CityLength FROM STATION ORDER BY CityLength ASC, CITY ASC LIMIT 1;
SELECT CITY, LENGTH(CITY) AS CityLength FROM STATION ORDER BY CityLength DESC, CITY ASC LIMIT 1;
*/

/* using union operator */
(SELECT CITY, LENGTH(CITY) AS CityLength FROM STATION ORDER BY CityLength ASC, CITY ASC LIMIT 1) UNION (SELECT CITY, LENGTH(CITY) AS CityLength FROM STATION ORDER BY CityLength DESC, CITY ASC LIMIT 1);
